/**
 * 日本酒・焼酎マスタデータ
 * Updated: 座標(axisX, axisY)と画像パス(image)を自動付与済み
 */
 const sakeData = [
  // =================================================================
  // 【松 - Premium】
  // =================================================================
  {
    id: "RES000019543",
    name: "十四代 純米大吟醸 極上諸白",
    kana: "じゅうよんだい ごくじょうもろはく",
    category_rank: "Matsu",
    type: "Sake",
    price_cost: 10102,
    capacity_ml: 1800,
    tags: ["最高峰", "希少", "要冷蔵", "山形"],
    sales_talk: "納品単価1万円超えの最高峰スペック。十四代の中でも特別な一本です。",
    pairing_hint: "素材の味を生かした繊細な料理、刺身の盛り合わせ",
    image: "", 
    axisX: 45, // バランス〜やや甘
    axisY: 95  // 非常に華やか
  },
  {
    id: "RES000015699",
    name: "十四代 純米大吟醸 龍の落と子 生",
    kana: "じゅうよんだい りゅうのおとしご なま",
    category_rank: "Matsu",
    type: "Sake",
    price_cost: 11110,
    capacity_ml: 1800,
    tags: ["自社開発米", "季節限定", "生酒", "要冷蔵", "山形"],
    sales_talk: "「龍の落と子」は十四代が自ら開発した独自の酒米。季節限定のフレッシュな生酒です。",
    pairing_hint: "乾杯の一杯、前菜",
    image: "",
    axisX: 40, 
    axisY: 90
  },
  {
    id: "RES000015638",
    name: "十四代 純米大吟醸 上諸白 播州愛山",
    kana: "じゅうよんだい ばんしゅうあいやま",
    category_rank: "Matsu",
    type: "Sake",
    price_cost: 6109,
    capacity_ml: 1800,
    tags: ["希少米", "愛山", "甘み", "コク", "要冷蔵", "山形"],
    sales_talk: "「愛山」という希少な酒米を使用。独特の甘みとコクがある高級酒です。",
    pairing_hint: "味のしっかりした煮物、肉料理",
    image: "",
    axisX: 25, // 甘み強め
    axisY: 85
  },
  {
    id: "RES000021183",
    name: "十四代 純米大吟醸 酒未来",
    kana: "じゅうよんだい さけみらい",
    category_rank: "Matsu",
    type: "Sake",
    price_cost: 5707,
    capacity_ml: 1800,
    tags: ["自社開発米", "フルーティー", "要冷蔵", "山形"],
    sales_talk: "「酒未来」は十四代の高木酒造が開発した酒米。華やかで未来を感じさせる味わいです。",
    pairing_hint: "白身魚のカルパッチョ",
    image: "",
    axisX: 40,
    axisY: 92
  },

  // =================================================================
  // 【竹 - Standard High】
  // =================================================================
  {
    id: "RES000020352",
    name: "作 純米吟醸 恵乃智",
    kana: "ざく めぐみのとも",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3800,
    capacity_ml: 1800,
    tags: ["フルーティー", "洋梨の香り", "三重"],
    sales_talk: "洋梨のようなふくよかな香りが特徴。華やかさを楽しみたい方におすすめです。",
    pairing_hint: "クリームチーズ、洋食",
    image: "",
    axisX: 35,
    axisY: 80
  },
  {
    id: "RES000015714",
    name: "作 純米吟醸 穂の智",
    kana: "ざく ほのとも",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3600,
    capacity_ml: 1800,
    tags: ["爽やか", "ライチの香り", "三重"],
    sales_talk: "ライチのような爽やかな香り。恵乃智よりすっきりとしていて飲みやすいです。",
    pairing_hint: "塩味の焼き鳥、天ぷら",
    image: "",
    axisX: 55,
    axisY: 75
  },
  {
    id: "RES000015837",
    name: "而今 特別純米 生原酒",
    kana: "じこん なまげんしゅ",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3400,
    capacity_ml: 1800,
    tags: ["人気No.1", "フレッシュ", "ジューシー", "要冷蔵", "三重"],
    sales_talk: "火入れなしの搾りたて。フレッシュでジューシーな、今しか飲めない味わいです。",
    pairing_hint: "トマトソース、揚げ物",
    image: "",
    axisX: 40,
    axisY: 85
  },
  {
    id: "RES000011556",
    name: "而今 特別純米 9号",
    kana: "じこん 9ごう",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3000,
    capacity_ml: 1800,
    tags: ["バランス", "食中酒", "要冷蔵", "三重"],
    sales_talk: "9号酵母由来の華やかすぎない香り。食事に寄り添うバランスの良い一本です。",
    pairing_hint: "和食全般",
    image: "",
    axisX: 50,
    axisY: 60
  },
  {
    id: "RES000015974",
    name: "而今 特別純米 おりがらみ",
    kana: "じこん おりがらみ",
    category_rank: "Take",
    type: "Sake",
    price_cost: 2900,
    capacity_ml: 1800,
    tags: ["季節限定", "薄濁り", "ガス感", "要冷蔵", "三重"],
    sales_talk: "冬〜春の限定酒。澱（おり）が絡んでおり、微発泡のガス感と米の旨味が楽しめます。",
    pairing_hint: "鍋料理、味の濃い料理",
    image: "",
    axisX: 30, // 旨味甘み
    axisY: 70
  },
  {
    id: "RES000011583",
    name: "みむろ杉 純米吟醸 山田錦",
    kana: "みむろすぎ やまだにしき",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3400,
    capacity_ml: 1800,
    tags: ["綺麗", "甘み", "王道", "奈良"],
    sales_talk: "酒米の王様・山田錦を使用。綺麗で澄んだ甘みのある、上品なお酒です。",
    pairing_hint: "出汁の効いた料理",
    image: "",
    axisX: 35,
    axisY: 70
  },
  {
    id: "RES000011561",
    name: "田酒 特別純米",
    kana: "でんしゅ とくべつじゅんまい",
    category_rank: "Take",
    type: "Sake",
    price_cost: 3300,
    capacity_ml: 1800,
    tags: ["伝統", "旨味", "食中酒", "青森"],
    sales_talk: "「日本酒のスタンダード」とも言える一本。米の旨味がしっかりしていて飲み飽きしません。",
    pairing_hint: "味噌味の料理、煮魚",
    image: "",
    axisX: 55,
    axisY: 40 // 落ち着いた香り
  },

  // =================================================================
  // 【梅 - Casual/Rotation】
  // =================================================================
  {
    id: "RES000011567",
    name: "播州一献 純米 超辛口",
    kana: "ばんしゅういっこん ちょうからくち",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2800,
    capacity_ml: 1800,
    tags: ["超辛口", "キレ", "食中酒", "兵庫"],
    sales_talk: "商品名に『超辛口』とある通り、キレ味抜群。食事の脂をさらっと流してくれます。",
    pairing_hint: "脂の乗った肉、揚げ物",
    image: "",
    axisX: 95, // 超辛い
    axisY: 20  // 穏やか
  },
  {
    id: "RES000020434",
    name: "みむろ杉 特別純米 辛口",
    kana: "みむろすぎ からくち",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2700,
    capacity_ml: 1800,
    tags: ["辛口", "露葉風", "キレ", "奈良"],
    sales_talk: "華やかな香りが多いみむろ杉の中で、あえて食事に合うようキレを出した辛口タイプです。",
    pairing_hint: "焼き鳥（塩）、白身魚",
    image: "",
    axisX: 85,
    axisY: 50
  },
  {
    id: "RES000011545",
    name: "磯自慢 本醸造",
    kana: "いそじまん ほんじょうぞう",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2400,
    capacity_ml: 1800,
    tags: ["定番", "キレ", "静岡"],
    sales_talk: "静岡を代表する銘酒。本醸造ならではのキレの良さと、吟醸酒のような上品な香りのバランスが絶妙です。",
    pairing_hint: "刺身、寿司",
    image: "",
    axisX: 75,
    axisY: 60
  },
  {
    id: "RES000011597",
    name: "酔鯨 特別本醸造",
    kana: "すいげい とくべつほんじょうぞう",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2200,
    capacity_ml: 1800,
    tags: ["酸味", "キレ", "高知"],
    sales_talk: "高知のお酒らしい、しっかりとした酸味とキレ。食事と一緒に飲むことで真価を発揮します。",
    pairing_hint: "カツオのたたき、油っぽい料理",
    image: "",
    axisX: 80,
    axisY: 30
  },
  {
    id: "RES000011543",
    name: "九頭龍 逸品",
    kana: "くずりゅう いっぴん",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2000,
    capacity_ml: 1800,
    tags: ["スッキリ", "お燗おすすめ", "黒龍", "福井"],
    sales_talk: "有名な『黒龍』の別ブランド。スッキリしていて、冷やでもお燗でも美味しい万能タイプです。",
    pairing_hint: "おでん、出し巻き卵",
    image: "",
    axisX: 60,
    axisY: 10 // 非常に穏やか
  },
  {
    id: "RES000011594",
    name: "紀土 純米",
    kana: "きっど じゅんまい",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 2000,
    capacity_ml: 1800,
    tags: ["優しい", "柔らかい", "初心者向け", "和歌山"],
    sales_talk: "口当たりが優しく、柔らかい味わい。飲み疲れしないので、ゆっくり飲みたい時におすすめです。",
    pairing_hint: "野菜の煮物、豆腐料理",
    image: "",
    axisX: 30,
    axisY: 40
  },
  {
    id: "RES000011584",
    name: "風の森 純米 秋津穂",
    kana: "かぜのもり あきつほ",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 1400,
    capacity_ml: 720,
    tags: ["ガス感", "微発泡", "フレッシュ", "高回転", "奈良"],
    sales_talk: "開栓直後のシュワッとした微発泡感が特徴。洋食やチーズにも合うモダンな日本酒です。",
    pairing_hint: "チーズ、カルパッチョ、ピザ",
    image: "",
    axisX: 40,
    axisY: 75
  },
  {
    id: "RES000019672",
    name: "KD 来楽ケグドラフト・スパークリング",
    kana: "けぐどらふと",
    category_rank: "Ume",
    type: "Sake",
    price_cost: 25000,
    capacity_ml: 10000,
    tags: ["スパークリング", "樽生", "乾杯", "兵庫"],
    sales_talk: "サーバーから注ぐ樽生のスパークリング日本酒。乾杯に最適です。",
    pairing_hint: "乾杯、前菜",
    image: "",
    axisX: 45,
    axisY: 65
  },

  // =================================================================
  // 【焼酎 - Shochu】
  // =================================================================
  {
    id: "RES000011518",
    name: "佐藤 黒麹",
    kana: "さとう くろ",
    category_rank: "Shochu_Imo",
    type: "Shochu",
    price_cost: 3600,
    capacity_ml: 1800,
    tags: ["芋", "黒麹", "どっしり", "香ばしい"],
    sales_talk: "どっしりとしたボディと香ばしさが特徴。「しっかりめ」の芋焼酎がお好きな方に。",
    pairing_hint: "豚の角煮、濃い味付けの料理",
    image: "",
    axisX: 80, // どっしり
    axisY: 80  // 香り強い
  },
  {
    id: "RES000011513",
    name: "富乃宝山",
    kana: "とみのほうざん",
    category_rank: "Shochu_Imo",
    type: "Shochu",
    price_cost: 3480,
    capacity_ml: 1800,
    tags: ["芋", "柑橘系", "ソーダ割おすすめ", "人気"],
    sales_talk: "柑橘系の爽やかな香り。焼酎初心者や女性にも大人気で、ソーダ割りが特におすすめです。",
    pairing_hint: "サラダ、洋食",
    image: "",
    axisX: 40,
    axisY: 90 // 柑橘香
  },
  {
    id: "RES000002401",
    name: "伊佐美",
    kana: "いさみ",
    category_rank: "Shochu_Imo",
    type: "Shochu",
    price_cost: 3065,
    capacity_ml: 1800,
    tags: ["芋", "元祖プレミアム", "バランス"],
    sales_talk: "元祖プレミアム焼酎。バランスが良く飲みやすい、王道の芋焼酎です。",
    pairing_hint: "和食全般",
    image: "",
    axisX: 50,
    axisY: 60
  },
  {
    id: "RES000011525",
    name: "安田",
    kana: "やすだ",
    category_rank: "Shochu_Imo",
    type: "Shochu",
    price_cost: 2920,
    capacity_ml: 1800,
    tags: ["芋", "蔓無源氏", "ライチの香り", "個性派"],
    sales_talk: "「蔓無源氏（つるなしげんじ）」という希少な芋を使用。ライチのような強烈な果実香がある個性派です。",
    pairing_hint: "スパイシーな料理、エスニック",
    image: "",
    axisX: 30,
    axisY: 98 // 強烈な香り
  },
  {
    id: "RES000011536",
    name: "三岳",
    kana: "みたけ",
    category_rank: "Shochu_Imo",
    type: "Shochu",
    price_cost: 2900,
    capacity_ml: 1800,
    tags: ["芋", "屋久島", "スッキリ", "お湯割り"],
    sales_talk: "屋久島の焼酎。スッキリして飲みやすく、お湯割りにすると甘みが引き立ちます。",
    pairing_hint: "さつま揚げ、焼き魚",
    image: "",
    axisX: 60,
    axisY: 40
  },
  {
    id: "RES000011519",
    name: "佐藤 麦",
    kana: "さとう むぎ",
    category_rank: "Shochu_Mugi",
    type: "Shochu",
    price_cost: 2955,
    capacity_ml: 1800,
    tags: ["麦", "香ばしい", "甘み"],
    sales_talk: "麦の香ばしさと、素直な甘みを感じられます。",
    pairing_hint: "焼き鳥（タレ）、燻製",
    image: "",
    axisX: 50,
    axisY: 50
  },
  {
    id: "RES000001711",
    name: "兼八",
    kana: "かねはち",
    category_rank: "Shochu_Mugi",
    type: "Shochu",
    price_cost: 2900,
    capacity_ml: 1800,
    tags: ["麦", "香ばしい", "麦チョコ", "人気"],
    sales_talk: "「麦チョコ」のようなロースト感（香ばしさ）が非常に強い、熱狂的なファンの多い銘柄です。",
    pairing_hint: "チョコレート、ローストビーフ",
    image: "",
    axisX: 60,
    axisY: 85 // ロースト香
  },
  {
    id: "RES000011515",
    name: "中々",
    kana: "なかなか",
    category_rank: "Shochu_Mugi",
    type: "Shochu",
    price_cost: 2580,
    capacity_ml: 1800,
    tags: ["麦", "上品", "軽やか", "百年の孤独"],
    sales_talk: "上品で軽やかな味わい。あの有名なプレミアム焼酎『百年の孤独』の原酒となる焼酎です。",
    pairing_hint: "豆腐料理、刺身",
    image: "",
    axisX: 45,
    axisY: 30
  },
  {
    id: "RES000018921",
    name: "れんと 黒糖焼酎",
    kana: "れんと",
    category_rank: "Shochu_Other",
    type: "Shochu",
    price_cost: 2000,
    capacity_ml: 1800,
    tags: ["黒糖", "音響熟成", "甘い香り"],
    sales_talk: "音響熟成で知られる黒糖焼酎。甘い香りと軽い口当たりで飲みやすいです。",
    pairing_hint: "デザート、豚肉料理",
    image: "",
    axisX: 20, // 甘い
    axisY: 50
  },
  {
    id: "RES000011539",
    name: "田酒 焼酎",
    kana: "でんしゅ しょうちゅう",
    category_rank: "Shochu_Other",
    type: "Shochu",
    price_cost: 2000,
    capacity_ml: 720,
    tags: ["粕取り", "吟醸香", "希少"],
    sales_talk: "日本酒「田酒」の酒粕から作られた焼酎。日本酒のような華やかな吟醸香があります。",
    pairing_hint: "日本酒好きな方への変化球として",
    image: "",
    axisX: 40,
    axisY: 80
  },

  // =================================================================
  // 【リキュール - Liqueur】
  // =================================================================
  {
    id: "RES000015308",
    name: "山田十郎 梅酒",
    kana: "やまだじゅうろう うめしゅ",
    category_rank: "Liqueur",
    type: "Liqueur",
    price_cost: 3300,
    capacity_ml: 1800,
    tags: ["梅酒", "神奈川"],
    sales_talk: "神奈川県産の梅を使用した、バランスの良い梅酒です。",
    pairing_hint: "ロック、ソーダ割り",
    image: "",
    axisX: 20,
    axisY: 50
  },
  {
    id: "RES000015687",
    name: "鶴梅 柚子",
    kana: "つるうめ ゆず",
    category_rank: "Liqueur",
    type: "Liqueur",
    price_cost: 3200,
    capacity_ml: 1800,
    tags: ["柚子", "濃厚", "人気No.1"],
    sales_talk: "当店人気No.1のリキュール。柚子の果汁感が濃厚で、ジュースのように飲みやすいです。",
    pairing_hint: "食後酒、デザート代わり",
    image: "",
    axisX: 10, // 甘酸っぱい
    axisY: 95
  },
  {
    id: "RES000014351",
    name: "青谷の梅",
    kana: "あおだにのうめ",
    category_rank: "Liqueur",
    type: "Liqueur",
    price_cost: 2500,
    capacity_ml: 1800,
    tags: ["梅酒", "京都", "芳醇"],
    sales_talk: "京都・城陽の梅酒。7年熟成の芳醇な味わいが特徴です。",
    pairing_hint: "ロックでじっくり",
    image: "",
    axisX: 15,
    axisY: 60
  }
];

export default sakeData;
